from django.core.management.base import BaseCommand
# from faker import Faker
from django.contrib.auth.models import User
from general.models import *
from personnel.models import *
from orders.models import *

class Command(BaseCommand):
    help = 'Seed the database with dummy data'

    def handle(self, *args, **kwargs):
        # fake = Faker()
        users = []

        # Create Users
        # for _ in range(10):
        #     user = User.objects.create_user(username=fake.user_name(), password=fake.password())
        #     users.append(user)

        # Create Office Categories
        rows = [
            {'category': 'Command', 'ordering': 1, },
            {'category': 'Coordinating Staff', 'ordering': 2, },
            {'category': 'Personal Staff', 'ordering': 3, },
            {'category': 'Special Staff', 'ordering': 4, },
            {'category': 'UCs', 'ordering': 5, },
            {'category': 'WSSUs', 'ordering': 6, },
            {'category': 'MS', 'ordering': 7, },
            {'category': 'Corps', 'ordering': 8, },
        ]
            
        for row in rows:
            obj, created = OfficeCategory.objects.update_or_create(
                category=row['category'], defaults=row
            )

        # Offices
        rows = [
            {'office': 'Army', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='MS'), 'program': '1'},
            {'office': 'Air Force', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='MS'), 'program': '2'},
            {'office': 'Navy', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='MS'), 'program': '3'},
            {'office': 'OCS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Command'), 'program': '4'},
            {'office': 'OVCS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Command'), 'program': '4'},
            {'office': 'OTDCS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Command'), 'program': '4'},
            {'office': 'OC1', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC2', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC3', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC4', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC5', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC6', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC7', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC8', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC9', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'OC10', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Coordinating Staff'), 'program': '4'},
            {'office': 'SM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Personal Staff'), 'program': '4'},
            {'office': 'OESPA', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Personal Staff'), 'program': '4'},
            {'office': 'OLA', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Personal Staff'), 'program': '4'},
            {'office': 'OSJS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Personal Staff'), 'program': '4'},
            {'office': 'OSSSM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Personal Staff'), 'program': '4'},
            {'office': 'OTIA', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Personal Staff'), 'program': '4'},
            {'office': 'OTIG', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Personal Staff'), 'program': '4'},
            {'office': 'PAO', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Personal Staff'), 'program': '4'},
            {'office': 'CC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'CLOAC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'EBSO', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'IMAC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'PDO', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'REO', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'SEO', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'SJPSCC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'GHQPFO', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'GHQSAO', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'ODPROF', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OSPS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTAG', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTCCHS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTCDS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTCE', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTCN', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTJAG', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTPMG', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTQMG', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'OTSG', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Special Staff'), 'program': '4'},
            {'office': 'NCOM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='UCs'), 'program': '4'},
            {'office': 'SCOM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='UCs'), 'program': '4'},
            {'office': 'WCOM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='UCs'), 'program': '4'},
            {'office': 'VCOM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='UCs'), 'program': '4'},
            {'office': 'EMCOM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='UCs'), 'program': '4'},
            {'office': 'WMCOM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='UCs'), 'program': '4'},
            {'office': 'JTF', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='UCs'), 'program': '4'},
            {'office': 'AC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'CES', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'CyG', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'ETDC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'FC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'MC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'LSC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'PGMC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'PKOC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'PS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'RESCOM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'CEISS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'CRS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'HSC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'IS', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'PMA', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='WSSUs'), 'program': '4'},
            {'office': 'PSC', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Corps'), 'program': '4'},
            {'office': 'SOCOM', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Corps'), 'program': '4'},
            {'office': 'CIG', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Corps'), 'program': '4'},
            {'office': 'GADO', 'office_name': None, 'office_category': OfficeCategory.objects.get(category='Corps'), 'program': '4'},
        ]

        # Create Offices
        for row in rows:
            obj, created = Office.objects.update_or_create(
                office=row['office'], defaults=row
            )

        # Define Ranks Data
        rows = [
            {'rank':'GEN', 'rank_full':'General', 'grade':'10', 'type':'Officer'},
            {'rank':'ADM', 'rank_full':'Admiral', 'grade':'10', 'type':'Officer'},
            {'rank':'LTGEN', 'rank_full':'Lieutenant General', 'grade':'9', 'type':'Officer'},
            {'rank':'VADM', 'rank_full':'Vice Admiral', 'grade':'9', 'type':'Officer'},
            {'rank':'MGEN', 'rank_full':'Major General', 'grade':'8', 'type':'Officer'},
            {'rank':'RADM', 'rank_full':'Rear Admiral', 'grade':'8', 'type':'Officer'},
            {'rank':'BGEN', 'rank_full':'Brigadier General', 'grade':'7', 'type':'Officer'},
            {'rank':'COMMO', 'rank_full':'Commodore', 'grade':'7', 'type':'Officer'},
            {'rank':'COL', 'rank_full':'Colonel', 'grade':'6', 'type':'Officer'},
            {'rank':'CAPT', 'rank_full':'Captain', 'grade':'6', 'type':'Officer'},
            {'rank':'LTC', 'rank_full':'Lieutenant Colonel', 'grade':'5', 'type':'Officer'},
            {'rank':'CDR', 'rank_full':'Commander', 'grade':'5', 'type':'Officer'},
            {'rank':'MAJ', 'rank_full':'Major', 'grade':'4', 'type':'Officer'},
            {'rank':'LCDR', 'rank_full':'Lieutenant Commander', 'grade':'4', 'type':'Officer'},
            {'rank':'CPT', 'rank_full':'Captain', 'grade':'3', 'type':'Officer'},
            {'rank':'LT', 'rank_full':'Lieutenant', 'grade':'3', 'type':'Officer'},
            {'rank':'1LT', 'rank_full':'First Lieutenant', 'grade':'2', 'type':'Officer'},
            {'rank':'LTJG', 'rank_full':'Lieutenant Junior Grade', 'grade':'2', 'type':'Officer'},
            {'rank':'2LT', 'rank_full':'Second Lieutenant', 'grade':'1', 'type':'Officer'},
            {'rank':'ENS', 'rank_full':'Ensign', 'grade':'1', 'type':'Officer'},
            {'rank':'FCMS', 'rank_full':'First Chief Master Sergeant', 'grade':'10', 'type':'EP'},
            {'rank':'CMSg', 'rank_full':'Chief Master Sergeant', 'grade':'9', 'type':'EP'},
            {'rank':'MCPO', 'rank_full':'Master Chief Petty Officer', 'grade':'9', 'type':'EP'},
            {'rank':'SMSg', 'rank_full':'Senior Master Sergeant', 'grade':'8', 'type':'EP'},
            {'rank':'SCPO', 'rank_full':'Senior Chief Petty Officer', 'grade':'8', 'type':'EP'},
            {'rank':'CPO', 'rank_full':'Chief Petty Officer', 'grade':'7', 'type':'EP'},
            {'rank':'MSg', 'rank_full':'Master Sergeant', 'grade':'7', 'type':'EP'},
            {'rank':'TSg', 'rank_full':'Technical Sergeant', 'grade':'6', 'type':'EP'},
            {'rank':'PO1', 'rank_full':'Petty officer, first class', 'grade':'6', 'type':'EP'},
            {'rank':'SSg', 'rank_full':'Staff Sergeant', 'grade':'5', 'type':'EP'},
            {'rank':'PO2', 'rank_full':'Petty officer, second class', 'grade':'5', 'type':'EP'},
            {'rank':'Sgt', 'rank_full':'Sergeant', 'grade':'4', 'type':'EP'},
            {'rank':'PO3', 'rank_full':'Petty officer, third class', 'grade':'4', 'type':'EP'},
            {'rank':'Cpl', 'rank_full':'Corporal', 'grade':'3', 'type':'EP'},
            {'rank':'A1C', 'rank_full':'Airman First Class', 'grade':'3', 'type':'EP'},
            {'rank':'SN1', 'rank_full':'Seaman First Class', 'grade':'3', 'type':'EP'},
            {'rank':'AW1C', 'rank_full':'Airwoman First Class', 'grade':'3', 'type':'EP'},
            {'rank':'FN1', 'rank_full':'Fireman First Class', 'grade':'3', 'type':'EP'},
            {'rank':'Pfc', 'rank_full':'Private First Class', 'grade':'2', 'type':'EP'},
            {'rank':'A2C', 'rank_full':'Airman Second Class', 'grade':'2', 'type':'EP'},
            {'rank':'SN2', 'rank_full':'Seaman Second Class', 'grade':'2', 'type':'EP'},
            {'rank':'AW2C', 'rank_full':'Airwoman Second Class', 'grade':'2', 'type':'EP'},
            {'rank':'FN2', 'rank_full':'Fireman Second Class', 'grade':'2', 'type':'EP'},
            {'rank':'Pvt', 'rank_full':'Private', 'grade':'1', 'type':'EP'},
            {'rank':'AM', 'rank_full':'Airman', 'grade':'1', 'type':'EP'},
            {'rank':'ASN', 'rank_full':'Apprentice Seaman', 'grade':'1', 'type':'EP'},
            {'rank':'AW', 'rank_full':'Airwoman', 'grade':'1', 'type':'EP'},
            {'rank':'AF', 'rank_full':'Apprentice Fireman', 'grade':'1', 'type':'EP'},
            {'rank':'Mr', 'rank_full':'Mister', 'grade':'1', 'type':'CHR'},
            {'rank':'Ms', 'rank_full':'Miss', 'grade':'1', 'type':'CHR'},
        ]
        
        # Create or get Rank objects
        for row in rows:
            obj, created = Rank.objects.update_or_create(
                rank=row['rank'], defaults=row
            )
            
        # Create BOS
        rows = [
            {'bos':'PA', 'ms':'PA'},
            {'bos':'PN', 'ms':'PN'},
            {'bos':'PN(M)', 'ms':'PN'},
            {'bos':'PAF', 'ms':'PAF'},
            {'bos':'JAGS', 'ms':'TAS'},
            {'bos':'MC', 'ms':'TAS'},
            {'bos':'NC', 'ms':'TAS'},
            {'bos':'MAC', 'ms':'TAS'},
            {'bos':'DS', 'ms':'TAS'},
            {'bos':'VC', 'ms':'TAS'},
            {'bos':'CHS', 'ms':'TAS'},
            {'bos':'PROF', 'ms':'TAS'},
            {'bos':'CHR', 'ms':'CHR'},
        ]
        for row in rows:
            obj, created = BOS.objects.update_or_create(
                bos=row['bos'], defaults=row
            )

        # Options
        rows = [
            {'app_name':'Personnel Strength Reporting System', 'app_brand':'PSRS', 'app_description':'', 'app_logo':'logo/default-logo.png', 'theme':'dark', 'theme_color':'navy', 'upload_max_size':'5120'},
        ]
        for row in rows:
            obj, created = Option.objects.update_or_create(
                app_brand=row['app_brand'], defaults=row
            )

        # Positions
        rows = [
            {'position':'Accountant I', 'description':'Accountant I', 'parenthetical':None, 'grade':12, }, 
            {'position':'Accountant II', 'description':'Accountant II', 'parenthetical':None, 'grade':16, }, 
            {'position':'Accountant III', 'description':'Accountant III', 'parenthetical':None, 'grade':19, }, 
            {'position':'Accountant IV', 'description':'Accountant IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Administrative Aide  III', 'description':'Administrative Aide  III', 'parenthetical':None, 'grade':3, }, 
            {'position':'Administrative Aide  III', 'description':'Administrative Aide  III', 'parenthetical':'Utility Worker II', 'grade':3, }, 
            {'position':'Administrative Aide  IV', 'description':'Administrative Aide  IV', 'parenthetical':None, 'grade':4, }, 
            {'position':'Administrative Aide  IV', 'description':'Administrative Aide  IV', 'parenthetical':'Mechanical Plant Operator I', 'grade':4, }, 
            {'position':'Administrative Aide  VI', 'description':'Administrative Aide  VI', 'parenthetical':'Storekeeper II', 'grade':6, }, 
            {'position':'Administrative Aide  VI', 'description':'Administrative Aide  VI', 'parenthetical':'Utility Foreman', 'grade':6, }, 
            {'position':'Administrative Aide  VI', 'description':'Administrative Aide  VI', 'parenthetical':'Welder II', 'grade':6, }, 
            {'position':'Administrative Aide III', 'description':'Administrative Aide III', 'parenthetical':'Administrative Aide III', 'grade':3, }, 
            {'position':'Administrative Aide III', 'description':'Administrative Aide III', 'parenthetical':'Audio-Visual Eqpt Optr I', 'grade':3, }, 
            {'position':'Administrative Aide III', 'description':'Administrative Aide III', 'parenthetical':'Clerk I', 'grade':3, }, 
            {'position':'Administrative Aide III', 'description':'Administrative Aide III', 'parenthetical':'Driver I', 'grade':3, }, 
            {'position':'Administrative Aide III', 'description':'Administrative Aide III', 'parenthetical':'Paper Cutting Mach Optr I', 'grade':3, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Accounting Clerk I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Aux Mach Optr I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Bookbinder II', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Budgeting Aide', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Buyer I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Clerk II', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Commo Eqpt Opr I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Driver II', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Electrician I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Fiscal Clerk I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Mechanic I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Printing Mach Optr I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Repro Mach Optr II', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Stenographer I', 'grade':4, }, 
            {'position':'Administrative Aide IV', 'description':'Administrative Aide IV', 'parenthetical':'Storekeeper I', 'grade':4, }, 
            {'position':'Administrative Aide IV (Driver)', 'description':'Administrative Aide IV (Driver)', 'parenthetical':'Driver', 'grade':4, }, 
            {'position':'Administrative Aide V', 'description':'Administrative Aide V', 'parenthetical':'Audio-Visual Eqpt Optr II', 'grade':5, }, 
            {'position':'Administrative Aide V', 'description':'Administrative Aide V', 'parenthetical':'Illustrator II', 'grade':5, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Accounting Clerk II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Acctg Clerk II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Air-Con Tech I', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Artist Illustrator I', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Audio-Visual Aids Tech I', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Aux Mach Optr II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Buyer II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Cash Clerk II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Clerk III', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Commo Eqpt Opr II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Commo Eqpt Optr II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Data Controller I', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'DEMO I', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Disbursing Offr I', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Elec & Commo Eqpt Tech I', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Electrician II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Fiscal Clerk II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Letter Carrier', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Mechanic II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Motorpool Dispatcher', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Stenographer II', 'grade':6, }, 
            {'position':'Administrative Aide VI', 'description':'Administrative Aide VI', 'parenthetical':'Storekeeper II', 'grade':6, }, 
            {'position':'Administrative Assistant I', 'description':'Administrative Assistant I', 'parenthetical':None, 'grade':7, }, 
            {'position':'Administrative Assistant I', 'description':'Administrative Assistant I', 'parenthetical':'Audio-Visual Eqpt Optr III', 'grade':7, }, 
            {'position':'Administrative Assistant I', 'description':'Administrative Assistant I', 'parenthetical':'Comptr Optr I', 'grade':7, }, 
            {'position':'Administrative Assistant I', 'description':'Administrative Assistant I', 'parenthetical':'Repro Mach Optr III', 'grade':7, }, 
            {'position':'Administrative Assistant I', 'description':'Administrative Assistant I', 'parenthetical':'Secretary I', 'grade':7, }, 
            {'position':'Administrative Assistant I', 'description':'Administrative Assistant I', 'parenthetical':'Steno Reporter I', 'grade':7, }, 
            {'position':'Administrative Assistant II', 'description':'', 'parenthetical':None, 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Accounting Clerk III', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Admin Asst', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Air-Con Tech II', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Artist Illustrator II', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Audio-Visual Aids Tech II', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Auto Equpment Inspector I', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Aux Mach Optr III', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Bookkeeper', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Budgeting Assistant', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Carpenter Foreman', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Clerk IV', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Data Controller II', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'DEMO II', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Disbursing Offr II', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Driver Courier III', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Elec & Commo Eqpt Tech II', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Fiscal Clerk III', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'HRM Asst I', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Hum Res Mgt Asst', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Human Resource Mgt Asst', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Mgmt & Audit Asst', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Mgt & Audit Asst I', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Painter Foreman', 'grade':8, }, 
            {'position':'Administrative Assistant II', 'description':'Administrative Assistant II', 'parenthetical':'Plumber Foreman', 'grade':8, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':None, 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Buyer III', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Comm Eqpt Opr III', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Commo Eqpt Optr III', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Comptr Optr II', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Electrician Foreman', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Mechanic III', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Secretary II', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Senior Bookkeeper', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Steno Reporter II', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Storekeeper III', 'grade':9, }, 
            {'position':'Administrative Assistant III', 'description':'Administrative Assistant III', 'parenthetical':'Welder Foreman', 'grade':9, }, 
            {'position':'Administrative Assistant IV', 'description':'Administrative Assistant IV', 'parenthetical':'Accounting Mach Optr III', 'grade':10, }, 
            {'position':'Administrative Assistant IV', 'description':'Administrative Assistant IV', 'parenthetical':'Audio-Visual Aids Tech III', 'grade':10, }, 
            {'position':'Administrative Assistant IV', 'description':'Administrative Assistant IV', 'parenthetical':'Carpenter Gen Foreman', 'grade':10, }, 
            {'position':'Administrative Assistant IV', 'description':'Administrative Assistant IV', 'parenthetical':'Painter General Foreman', 'grade':10, }, 
            {'position':'Administrative Assistant V', 'description':'Administrative Assistant V', 'parenthetical':'Aux Mach Optr IV', 'grade':11, }, 
            {'position':'Administrative Assistant V', 'description':'Administrative Assistant V', 'parenthetical':'Commo Eqpt Optr IV', 'grade':11, }, 
            {'position':'Administrative Assistant V', 'description':'Administrative Assistant V', 'parenthetical':'Data Controller III', 'grade':11, }, 
            {'position':'Administrative Assistant V', 'description':'Administrative Assistant V', 'parenthetical':'DEMO III', 'grade':11, }, 
            {'position':'Administrative Assistant V', 'description':'Administrative Assistant V', 'parenthetical':'Electrician Gen Foreman', 'grade':11, }, 
            {'position':'Administrative Assistant V', 'description':'Administrative Assistant V', 'parenthetical':"Mech'l Shop Foreman", 'grade':11, }, 
            {'position':'Administrative Assistant V', 'description':'Administrative Assistant V', 'parenthetical':'Steno Reporter III', 'grade':11, }, 
            {'position':'Administrative Assistant VI', 'description':'Administrative Assistant VI', 'parenthetical':'Comptr Optr III', 'grade':12, }, 
            {'position':'Administrative Officer  I', 'description':'Administrative Officer  I', 'parenthetical':'Cashier I', 'grade':10, }, 
            {'position':'Administrative Officer  I', 'description':'Administrative Officer  I', 'parenthetical':'Records Officer I', 'grade':10, }, 
            {'position':'Administrative Officer  I', 'description':'Administrative Officer  I', 'parenthetical':'Records Offr I', 'grade':10, }, 
            {'position':'Administrative Officer  I', 'description':'Administrative Officer  I', 'parenthetical':'Supply Officer I', 'grade':10, }, 
            {'position':'Administrative Officer  I', 'description':'Administrative Officer  I', 'parenthetical':'Supply Offr I', 'grade':10, }, 
            {'position':'Administrative Officer  II', 'description':'Administrative Officer  II', 'parenthetical':'Administrative Officer  I', 'grade':11, }, 
            {'position':'Administrative Officer  II', 'description':'Administrative Officer  II', 'parenthetical':'Budget Officer I', 'grade':11, }, 
            {'position':'Administrative Officer  II', 'description':'Administrative Officer  II', 'parenthetical':'Budget Offr I', 'grade':11, }, 
            {'position':'Administrative Officer  II', 'description':'Administrative Officer  II', 'parenthetical':'Hum Res Mgt Offr I', 'grade':11, }, 
            {'position':'Administrative Officer  II', 'description':'Administrative Officer  II', 'parenthetical':'Info Offr I', 'grade':11, }, 
            {'position':'Administrative Officer  II', 'description':'Administrative Officer  II', 'parenthetical':'Mgmt & Audit Analyst I', 'grade':11, }, 
            {'position':'Administrative Officer  II', 'description':'Administrative Officer  II', 'parenthetical':'Mgt & Audit Analyst I', 'grade':11, }, 
            {'position':'Administrative Officer  III', 'description':'Administrative Officer  III', 'parenthetical':None, 'grade':14, }, 
            {'position':'Administrative Officer  III', 'description':'Administrative Officer  III', 'parenthetical':'Records Offr II', 'grade':14, }, 
            {'position':'Administrative Officer  III', 'description':'Administrative Officer  III', 'parenthetical':'Supply Offr II', 'grade':14, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':None, 'grade':15, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':'Administrative Officer II', 'grade':15, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':'Budget Officer II', 'grade':15, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':'Budget Offr II', 'grade':15, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':'Hum Res Mgt Offr II', 'grade':15, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':'Human Resource Mgt Offr II', 'grade':15, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':'Info Offr II', 'grade':15, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':'MAA II', 'grade':15, }, 
            {'position':'Administrative Officer  IV', 'description':'Administrative Officer  IV', 'parenthetical':'Mgt & Audit Analyst II', 'grade':15, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Administrative Officer III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Budget Officer III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Budget Offr III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Fiscal Controller III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Hum Res Mgt Offr III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Info Offr III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Mgt & Audit Analyst III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Records Offr III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Supply Officer III', 'grade':18, }, 
            {'position':'Administrative Officer  V', 'description':'Administrative Officer  V', 'parenthetical':'Supply Offr III', 'grade':18, }, 
            {'position':'Administrative Officer I', 'description':'Administrative Officer I', 'parenthetical':None, 'grade':10, }, 
            {'position':'Administrative Officer II', 'description':'', 'parenthetical':None, 'grade':11, }, 
            {'position':'Administrative Officer II', 'description':'Administrative Officer II', 'parenthetical':None, 'grade':11, }, 
            {'position':'Administrative Officer II', 'description':'Administrative Officer II', 'parenthetical':'Financial Analyst I', 'grade':11, }, 
            {'position':'Administrative Officer II', 'description':'Administrative Officer II', 'parenthetical':'Fiscal Examiner I', 'grade':11, }, 
            {'position':'Administrative Officer II', 'description':'Administrative Officer II', 'parenthetical':'HRMO I', 'grade':11, }, 
            {'position':'Administrative Officer IV', 'description':'', 'parenthetical':None, 'grade':15, }, 
            {'position':'Administrative Officer IV', 'description':'Administrative Officer IV', 'parenthetical':'Fiscal Examiner II', 'grade':15, }, 
            {'position':'Administrative Officer IV', 'description':'Administrative Officer IV', 'parenthetical':'HRMO II', 'grade':15, }, 
            {'position':'Administrative Officer V', 'description':'Administrative Officer V', 'parenthetical':'HRMO III', 'grade':18, }, 
            {'position':'Architect I', 'description':'Architect I', 'parenthetical':None, 'grade':12, }, 
            {'position':'Architect II', 'description':'Architect II', 'parenthetical':None, 'grade':16, }, 
            {'position':'Architect III', 'description':'Architect III', 'parenthetical':None, 'grade':19, }, 
            {'position':'Architect IV', 'description':'Architect IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Artf?l L&B Mkr II', 'description':'Artf?l L&B Mkr II', 'parenthetical':None, 'grade':6, }, 
            {'position':'Artf?l Lim & Brace Maker I', 'description':'Artf?l Lim & Brace Maker I', 'parenthetical':None, 'grade':4, }, 
            {'position':'Assistant Financial Claims Examiner', 'description':'Assistant Financial Claims Examiner', 'parenthetical':None, 'grade':7, }, 
            {'position':'Assistant Professor I', 'description':'Assistant Professor I', 'parenthetical':None, 'grade':15, }, 
            {'position':'Assistant Professor II', 'description':'Assistant Professor II', 'parenthetical':None, 'grade':16, }, 
            {'position':'Assistant Professor III', 'description':'Assistant Professor III', 'parenthetical':None, 'grade':17, }, 
            {'position':'Assistant Professor IV', 'description':'Assistant Professor IV', 'parenthetical':None, 'grade':18, }, 
            {'position':'Assistant Statistician', 'description':'Assistant Statistician', 'parenthetical':None, 'grade':9, }, 
            {'position':'Associate Professor I', 'description':'Associate Professor I', 'parenthetical':None, 'grade':19, }, 
            {'position':'Associate Professor II', 'description':'Associate Professor II', 'parenthetical':None, 'grade':20, }, 
            {'position':'Associate Professor III', 'description':'Associate Professor III', 'parenthetical':None, 'grade':21, }, 
            {'position':'Associate Professor IV', 'description':'Associate Professor IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Associate Professor V', 'description':'Associate Professor V', 'parenthetical':None, 'grade':23, }, 
            {'position':'Attorney I', 'description':'Attorney I', 'parenthetical':None, 'grade':16, }, 
            {'position':'Attorney II', 'description':'Attorney II', 'parenthetical':None, 'grade':18, }, 
            {'position':'Attorney III', 'description':'Attorney III', 'parenthetical':None, 'grade':21, }, 
            {'position':'Attorney IV', 'description':'Attorney IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Automotive Equipment Inspector I', 'description':'Automotive Equipment Inspector I', 'parenthetical':None, 'grade':8, }, 
            {'position':'Ballistician I', 'description':'Ballistician I', 'parenthetical':None, 'grade':10, }, 
            {'position':'Broadcast Operations Technician I', 'description':'Broadcast Operations Technician I', 'parenthetical':None, 'grade':9, }, 
            {'position':'Broadcast Program Traffic Officer', 'description':'Broadcast Program Traffic Officer', 'parenthetical':None, 'grade':9, }, 
            {'position':"Broadcast Program/Prod Annc'r", 'description':"Broadcast Program/Prod Annc'r", 'parenthetical':None, 'grade':12, }, 
            {'position':'Cartographer I', 'description':'Cartographer I', 'parenthetical':None, 'grade':6, }, 
            {'position':'Cartographer II', 'description':'Cartographer II', 'parenthetical':None, 'grade':8, }, 
            {'position':'Chef', 'description':'Chef', 'parenthetical':None, 'grade':11, }, 
            {'position':'Chief Accountant', 'description':'Chief Accountant', 'parenthetical':None, 'grade':24, }, 
            {'position':'Chief Administrative Officer', 'description':'Chief Administrative Officer', 'parenthetical':None, 'grade':24, }, 
            {'position':'Chief Administrative Officer', 'description':'Chief Administrative Officer', 'parenthetical':'Budget Offr V', 'grade':24, }, 
            {'position':'Chief Administrative Officer', 'description':'Chief Administrative Officer', 'parenthetical':'Hum Res Mgt Offr V', 'grade':24, }, 
            {'position':'Chief Administrative Officer', 'description':'Chief Administrative Officer', 'parenthetical':'Mgt & Audit Analyst V', 'grade':24, }, 
            {'position':'Chief Administrative Officer', 'description':'Chief Administrative Officer', 'parenthetical':'Records Officer V', 'grade':24, }, 
            {'position':'Chief Administrative Officer', 'description':'Chief Administrative Officer', 'parenthetical':'Supply Offr V', 'grade':24, }, 
            {'position':"Chief of Med Prof'l Staff II", 'description':"Chief of Med Prof'l Staff II", 'parenthetical':None, 'grade':26, }, 
            {'position':'Civil Defense Officer IV', 'description':'Civil Defense Officer IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Community Development Officer I', 'description':'Community Development Officer I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Community Development Officer II', 'description':'Community Development Officer II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Community Development Officer III', 'description':'Community Development Officer III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Community Development Officer IV', 'description':'Community Development Officer IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Computer Maint Technologist I', 'description':'Computer Maint Technologist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Computer Maint Technologist II', 'description':'Computer Maint Technologist II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Computer Maint Technologist III', 'description':'Computer Maint Technologist III', 'parenthetical':None, 'grade':17, }, 
            {'position':'Computer Maintenance Technologist I', 'description':'Computer Maintenance Technologist I', 'parenthetical':'Computer Maintenance Technologist I', 'grade':11, }, 
            {'position':'Computer Programmer I', 'description':'Computer Programmer I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Computer Programmer I', 'description':'Computer Programmer I', 'parenthetical':'Computer Programmer I', 'grade':11, }, 
            {'position':'Computer Programmer II', 'description':'Computer Programmer II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Computer Programmer III', 'description':'Computer Programmer III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Const & Maint Foreman', 'description':'Const & Maint Foreman', 'parenthetical':None, 'grade':8, }, 
            {'position':'Const & Maint General Foreman', 'description':'Const & Maint General Foreman', 'parenthetical':None, 'grade':11, }, 
            {'position':'Cook I', 'description':'Cook I', 'parenthetical':None, 'grade':3, }, 
            {'position':'Cook I', 'description':'Cook I', 'parenthetical':'Cook I', 'grade':3, }, 
            {'position':'Cook II', 'description':'Cook II', 'parenthetical':None, 'grade':5, }, 
            {'position':'Cook II', 'description':'Cook II', 'parenthetical':'Cook II', 'grade':5, }, 
            {'position':'Copy Reader', 'description':'Copy Reader', 'parenthetical':None, 'grade':7, }, 
            {'position':'Defense Research Officer I', 'description':'Defense Research Officer I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Defense Research Officer I', 'description':'Defense Research Officer I', 'parenthetical':'Defense Research Officer I', 'grade':11, }, 
            {'position':'Defense Research Officer II', 'description':'Defense Research Officer II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Dental Aide', 'description':'Dental Aide', 'parenthetical':None, 'grade':4, }, 
            {'position':'Dental Aide', 'description':'Dental Aide', 'parenthetical':'Dental Aide', 'grade':4, }, 
            {'position':'Dental Hygienist', 'description':'Dental Hygienist', 'parenthetical':None, 'grade':10, }, 
            {'position':'Dental Hygienist', 'description':'Dental Hygienist', 'parenthetical':'Dental Hygienist', 'grade':10, }, 
            {'position':'Dentist I', 'description':'Dentist I', 'parenthetical':None, 'grade':14, }, 
            {'position':'Dentist II', 'description':'Dentist II', 'parenthetical':None, 'grade':17, }, 
            {'position':'Dentist III', 'description':'Dentist III', 'parenthetical':None, 'grade':20, }, 
            {'position':'Dentist IV', 'description':'Dentist IV', 'parenthetical':None, 'grade':23, }, 
            {'position':'Director I', 'description':'Director I', 'parenthetical':None, 'grade':25, }, 
            {'position':'Draftsman I', 'description':'Draftsman I', 'parenthetical':None, 'grade':6, }, 
            {'position':'Draftsman I', 'description':'Draftsman I', 'parenthetical':'Draftsman I', 'grade':6, }, 
            {'position':'Draftsman II', 'description':'Draftsman II', 'parenthetical':None, 'grade':8, }, 
            {'position':'Driver I (Ambulance)', 'description':'Driver I (Ambulance)', 'parenthetical':'Driver I', 'grade':3, }, 
            {'position':'Educ Research Assistant I', 'description':'Educ Research Assistant I', 'parenthetical':None, 'grade':9, }, 
            {'position':'Engineer I', 'description':'Engineer I', 'parenthetical':None, 'grade':12, }, 
            {'position':'Engineer II', 'description':'Engineer II', 'parenthetical':None, 'grade':16, }, 
            {'position':'Engineer III', 'description':'Engineer III', 'parenthetical':None, 'grade':19, }, 
            {'position':'Engineer IV', 'description':'Engineer IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Engineer V', 'description':'Engineer V', 'parenthetical':None, 'grade':24, }, 
            {'position':'Engineering Assistant', 'description':'Engineering Assistant', 'parenthetical':None, 'grade':8, }, 
            {'position':'Financial Claims Examiner I', 'description':'Financial Claims Examiner I', 'parenthetical':None, 'grade':10, }, 
            {'position':'Financial Claims Examiner II', 'description':'Financial Claims Examiner II', 'parenthetical':None, 'grade':14, }, 
            {'position':'Food Service Supervisor I', 'description':'Food Service Supervisor I', 'parenthetical':None, 'grade':9, }, 
            {'position':'Food Service Supervisor I', 'description':'Food Service Supervisor I', 'parenthetical':'Food Service Supervisor I', 'grade':9, }, 
            {'position':'Food Svc Supervisor I', 'description':'Food Svc Supervisor I', 'parenthetical':None, 'grade':9, }, 
            {'position':'Freight Service Foreman', 'description':'Freight Service Foreman', 'parenthetical':None, 'grade':6, }, 
            {'position':'Guidance Counsellor II', 'description':'Guidance Counsellor II', 'parenthetical':None, 'grade':11, }, 
            {'position':'Guidance Service Specialist II', 'description':'', 'parenthetical':None, 'grade':18, }, 
            {'position':'Health Physicist I', 'description':'Health Physicist I', 'parenthetical':None, 'grade':15, }, 
            {'position':'History Researcher I', 'description':'History Researcher I', 'parenthetical':None, 'grade':10, }, 
            {'position':'History Researcher II', 'description':'History Researcher II', 'parenthetical':None, 'grade':14, }, 
            {'position':'Information Officer I', 'description':'Information Officer I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Information Officer I', 'description':'Information Officer I', 'parenthetical':'Information Officer I', 'grade':11, }, 
            {'position':'Information Systems Analyst I', 'description':'Information Systems Analyst I', 'parenthetical':None, 'grade':12, }, 
            {'position':'Information Systems Analyst II', 'description':'Information Systems Analyst II', 'parenthetical':None, 'grade':16, }, 
            {'position':'Information Systems Analyst III', 'description':'Information Systems Analyst III', 'parenthetical':None, 'grade':19, }, 
            {'position':'Information Systems Researcher I', 'description':'Information Systems Researcher I', 'parenthetical':None, 'grade':10, }, 
            {'position':'Information Technology Officer I', 'description':'Information Technology Officer I', 'parenthetical':None, 'grade':19, }, 
            {'position':'Information Technology Officer II', 'description':'Information Technology Officer II', 'parenthetical':None, 'grade':22, }, 
            {'position':'Instructor I', 'description':'Instructor I', 'parenthetical':None, 'grade':12, }, 
            {'position':'Instructor II', 'description':'Instructor II', 'parenthetical':None, 'grade':13, }, 
            {'position':'Instructor III', 'description':'Instructor III', 'parenthetical':None, 'grade':14, }, 
            {'position':'Intelligence Agent Aide', 'description':'Intelligence Agent Aide', 'parenthetical':None, 'grade':4, }, 
            {'position':'Intelligence Agent I', 'description':'Intelligence Agent I', 'parenthetical':None, 'grade':8, }, 
            {'position':'Intelligence Agent II', 'description':'Intelligence Agent II', 'parenthetical':None, 'grade':10, }, 
            {'position':'Intelligence Officer I', 'description':'Intelligence Officer I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Intelligence Officer II', 'description':'Intelligence Officer II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Intelligence Officer III', 'description':'Intelligence Officer III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Intelligence Officer IV', 'description':'Intelligence Officer IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Laboratory Aide II', 'description':'Laboratory Aide II', 'parenthetical':None, 'grade':4, }, 
            {'position':'Laboratory Aide II', 'description':'Laboratory Aide II', 'parenthetical':'Laboratory Aide II', 'grade':4, }, 
            {'position':'Laboratory Technician I', 'description':'Laboratory Technician I', 'parenthetical':None, 'grade':6, }, 
            {'position':'Laboratory Technician II', 'description':'Laboratory Technician II', 'parenthetical':None, 'grade':8, }, 
            {'position':'Laboratory Technician III', 'description':'Laboratory Technician III', 'parenthetical':None, 'grade':10, }, 
            {'position':'Legal Aide', 'description':'Legal Aide', 'parenthetical':None, 'grade':5, }, 
            {'position':'Legal Assistant I', 'description':'Legal Assistant I', 'parenthetical':None, 'grade':10, }, 
            {'position':'Legal Assistant II', 'description':'Legal Assistant II', 'parenthetical':None, 'grade':12, }, 
            {'position':'Librarian I', 'description':'Librarian I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Librarian I', 'description':'Librarian I', 'parenthetical':'Librarian I', 'grade':11, }, 
            {'position':'Librarian II', 'description':'Librarian II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Librarian III', 'description':'Librarian III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Logistics Management Officer I', 'description':'Logistics Management Officer I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Logistics Management Officer II', 'description':'Logistics Management Officer II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Logistics Management Officer III', 'description':'Logistics Management Officer III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Logistics Management Officer IV', 'description':'Logistics Management Officer IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Med Equip Tech I', 'description':'Med Equip Tech I', 'parenthetical':None, 'grade':6, }, 
            {'position':'Med Equip Tech II', 'description':'Med Equip Tech II', 'parenthetical':None, 'grade':8, }, 
            {'position':'Med Lab Tech I', 'description':'Med Lab Tech I', 'parenthetical':None, 'grade':6, }, 
            {'position':'Med Lab Tech II', 'description':'Med Lab Tech II', 'parenthetical':None, 'grade':8, }, 
            {'position':'Medical Center Chief II', 'description':'Medical Center Chief II', 'parenthetical':None, 'grade':27, }, 
            {'position':'Medical Equipment Technician I', 'description':'Medical Equipment Technician I', 'parenthetical':None, 'grade':6, }, 
            {'position':'Medical Equipment Technician II', 'description':'Medical Equipment Technician II', 'parenthetical':None, 'grade':8, }, 
            {'position':'Medical Laboratory Technician I', 'description':'Medical Laboratory Technician I', 'parenthetical':'Medical Laboratory Technician I', 'grade':6, }, 
            {'position':'Medical Officer I', 'description':'Medical Officer I', 'parenthetical':None, 'grade':16, }, 
            {'position':'Medical Officer II', 'description':'Medical Officer II', 'parenthetical':None, 'grade':18, }, 
            {'position':'Medical Officer III', 'description':'Medical Officer III', 'parenthetical':None, 'grade':21, }, 
            {'position':'Medical Specialist I', 'description':'Medical Specialist I', 'parenthetical':None, 'grade':22, }, 
            {'position':'Medical Specialist II', 'description':'Medical Specialist II', 'parenthetical':None, 'grade':23, }, 
            {'position':'Medical Specialist III', 'description':'Medical Specialist III', 'parenthetical':None, 'grade':24, }, 
            {'position':'Medical Specialist III (part-time)', 'description':'', 'parenthetical':None, 'grade':24, }, 
            {'position':'Medical Specialist IV', 'description':'Medical Specialist IV', 'parenthetical':None, 'grade':25, }, 
            {'position':'Medical Technologist I', 'description':'Medical Technologist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Medical Technologist I', 'description':'Medical Technologist I', 'parenthetical':'Medical Technologist I', 'grade':11, }, 
            {'position':'Medical Technologist II', 'description':'Medical Technologist II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Medical Technologist III', 'description':'', 'parenthetical':None, 'grade':18, }, 
            {'position':'Medical Technologist IV', 'description':'Medical Technologist IV', 'parenthetical':None, 'grade':20, }, 
            {'position':'Metal Worker II', 'description':'Metal Worker II', 'parenthetical':None, 'grade':6, }, 
            {'position':'Midwife I', 'description':'Midwife I', 'parenthetical':None, 'grade':9, }, 
            {'position':'Midwife I', 'description':'Midwife I', 'parenthetical':'Midwife I', 'grade':9, }, 
            {'position':'Midwife II', 'description':'Midwife II', 'parenthetical':None, 'grade':11, }, 
            {'position':'Munitions Operator II', 'description':'Munitions Operator II', 'parenthetical':None, 'grade':6, }, 
            {'position':'Munitions Production Tech I', 'description':'Munitions Production Tech I', 'parenthetical':None, 'grade':6, }, 
            {'position':'News Editor II', 'description':'News Editor II', 'parenthetical':None, 'grade':16, }, 
            {'position':'Nurse I', 'description':'Nurse I', 'parenthetical':None, 'grade':15, }, 
            {'position':'Nurse II', 'description':'Nurse II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Nurse III', 'description':'Nurse III', 'parenthetical':None, 'grade':17, }, 
            {'position':'Nurse IV', 'description':'Nurse IV', 'parenthetical':None, 'grade':19, }, 
            {'position':'Nurse V', 'description':'Nurse V', 'parenthetical':None, 'grade':20, }, 
            {'position':'Nursing Attendant I', 'description':'Nursing Attendant I', 'parenthetical':None, 'grade':4, }, 
            {'position':'Nursing Attendant I', 'description':'Nursing Attendant I', 'parenthetical':'Nursing Attendant I', 'grade':4, }, 
            {'position':'Nursing Attendant II', 'description':'Nursing Attendant II', 'parenthetical':None, 'grade':6, }, 
            {'position':'Nutritionist-Dietitian I', 'description':'Nutritionist-Dietitian I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Nutritionist-Dietitian I', 'description':'Nutritionist-Dietitian I', 'parenthetical':'Nutritionist-Dietitian I', 'grade':11, }, 
            {'position':'Nutritionist-Dietitian II', 'description':'', 'parenthetical':None, 'grade':15, }, 
            {'position':'Nutritionist-Dietitian III', 'description':'Nutritionist-Dietitian III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Nutritionist-Dietitian IV', 'description':'Nutritionist-Dietitian IV', 'parenthetical':None, 'grade':20, }, 
            {'position':'Occ Therapist I', 'description':'Occ Therapist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Occupational Therapist II', 'description':'Occupational Therapist II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Optometrist I', 'description':'Optometrist I', 'parenthetical':None, 'grade':12, }, 
            {'position':'Ordnance Technician I', 'description':'Ordnance Technician I', 'parenthetical':None, 'grade':6, }, 
            {'position':'Ordnance Technician II', 'description':'Ordnance Technician II', 'parenthetical':None, 'grade':8, }, 
            {'position':'Ordnance Technician III', 'description':'Ordnance Technician III', 'parenthetical':None, 'grade':11, }, 
            {'position':'Pharm Program Supervisor', 'description':'Pharm Program Supervisor', 'parenthetical':None, 'grade':22, }, 
            {'position':'Pharmacist I', 'description':'Pharmacist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Pharmacist I', 'description':'Pharmacist I', 'parenthetical':'Pharmacist I', 'grade':11, }, 
            {'position':'Pharmacist II', 'description':'Pharmacist II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Pharmacist III', 'description':'Pharmacist III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Pharmacist IV', 'description':'Pharmacist IV', 'parenthetical':None, 'grade':20, }, 
            {'position':'Photoengraver II', 'description':'Photoengraver II', 'parenthetical':None, 'grade':6, }, 
            {'position':'Photoengraver III', 'description':'Photoengraver III', 'parenthetical':None, 'grade':9, }, 
            {'position':'Physical Therapist I', 'description':'Physical Therapist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Physical Therapist I', 'description':'Physical Therapist I', 'parenthetical':'Physical Therapist I', 'grade':11, }, 
            {'position':'Physical Therapist II', 'description':'Physical Therapist II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Physical Therapist III', 'description':'Physical Therapist III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Planning Officer I', 'description':'Planning Officer I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Planning Officer I', 'description':'Planning Officer I', 'parenthetical':'Planning Officer I', 'grade':11, }, 
            {'position':'Planning Officer II', 'description':'Planning Officer II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Planning Officer III', 'description':'Planning Officer III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Planning Officer IV', 'description':'Planning Officer IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Prod Planning & Cntrl Asst', 'description':'Prod Planning & Cntrl Asst', 'parenthetical':None, 'grade':8, }, 
            {'position':'Production Cost Estimator I', 'description':'Production Cost Estimator I', 'parenthetical':None, 'grade':6, }, 
            {'position':'Professor I', 'description':'Professor I', 'parenthetical':None, 'grade':24, }, 
            {'position':'Professor II', 'description':'Professor II', 'parenthetical':None, 'grade':25, }, 
            {'position':'Professor II', 'description':'Professor II', 'parenthetical':'Professor II', 'grade':25, }, 
            {'position':'Professor III', 'description':'Professor III', 'parenthetical':'Professor III', 'grade':26, }, 
            {'position':'Psychologist I', 'description':'Psychologist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Psychologist I', 'description':'Psychologist I', 'parenthetical':'Psychologist I', 'grade':11, }, 
            {'position':'Psychologist II', 'description':'Psychologist II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Psychologist III', 'description':'Psychologist III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Rad Tech III', 'description':'Rad Tech III', 'parenthetical':None, 'grade':15, }, 
            {'position':'Radiologic Technologist I', 'description':'Radiologic Technologist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Radiologic Technologist I', 'description':'Radiologic Technologist I', 'parenthetical':'Radiologic Technologist I', 'grade':11, }, 
            {'position':'Radiologic Technologist II', 'description':'Radiologic Technologist II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Radiologic Technologist III', 'description':'', 'parenthetical':None, 'grade':18, }, 
            {'position':'Radiologic Technologist IV', 'description':'Radiologic Technologist IV', 'parenthetical':None, 'grade':18, }, 
            {'position':'Recrtn & Welfare Svcs Assistant', 'description':'Recrtn & Welfare Svcs Assistant', 'parenthetical':None, 'grade':7, }, 
            {'position':'Respiratory Therapist I', 'description':'Respiratory Therapist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Seamstress', 'description':'Seamstress', 'parenthetical':None, 'grade':2, }, 
            {'position':'Social Welfare Officer II', 'description':'Social Welfare Officer II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Social Welfare Officer III', 'description':'Social Welfare Officer III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Social Worker Officer I', 'description':'Social Worker Officer I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Special Investigator I', 'description':'Special Investigator I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Special Investigator II', 'description':'Special Investigator II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Speech Therapist I', 'description':'Speech Therapist I', 'parenthetical':None, 'grade':10, }, 
            {'position':'Speech Therapist II', 'description':'Speech Therapist II', 'parenthetical':None, 'grade':14, }, 
            {'position':'Sr Administrative Assistant I', 'description':'Sr Administrative Assistant I', 'parenthetical':None, 'grade':13, }, 
            {'position':'Sr Administrative Assistant I', 'description':'Sr Administrative Assistant I', 'parenthetical':'Buyer V', 'grade':13, }, 
            {'position':'Sr Administrative Assistant I', 'description':'Sr Administrative Assistant I', 'parenthetical':'Data Controller IV', 'grade':13, }, 
            {'position':'Sr Administrative Assistant I', 'description':'Sr Administrative Assistant I', 'parenthetical':'DEMO IV', 'grade':13, }, 
            {'position':'Sr Administrative Assistant I', 'description':'Sr Administrative Assistant I', 'parenthetical':'Steno Reporter IV', 'grade':13, }, 
            {'position':'Sr Administrative Assistant II', 'description':'Sr Administrative Assistant II', 'parenthetical':'Comptr Optr IV', 'grade':14, }, 
            {'position':'Sr Vet Assistance Officer III', 'description':'Sr Vet Assistance Officer III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Statistician Aide', 'description':'Statistician Aide', 'parenthetical':None, 'grade':4, }, 
            {'position':'Statistician I', 'description':'Statistician I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Statistician III', 'description':'Statistician III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Supervising Admin Offr', 'description':'Supervising Admin Offr', 'parenthetical':'BO IV', 'grade':22, }, 
            {'position':'Supervising Admin Offr', 'description':'Supervising Admin Offr', 'parenthetical':'HRMO IV', 'grade':22, }, 
            {'position':'Supervising Admin Offr', 'description':'Supervising Admin Offr', 'parenthetical':'MAA IV', 'grade':22, }, 
            {'position':'Supervising Admin Offr', 'description':'Supervising Admin Offr', 'parenthetical':'Supply Officer IV', 'grade':22, }, 
            {'position':'Supervising Administrative Officer', 'description':'Supervising Administrative Officer', 'parenthetical':'Budget Officer IV', 'grade':22, }, 
            {'position':'Supervising Administrative Officer', 'description':'Supervising Administrative Officer', 'parenthetical':'Budget Offr IV', 'grade':22, }, 
            {'position':'Supervising Administrative Officer', 'description':'Supervising Administrative Officer', 'parenthetical':'Hum Res Mgt Offr IV', 'grade':22, }, 
            {'position':'Supervising Administrative Officer', 'description':'Supervising Administrative Officer', 'parenthetical':'Mgt & Audit Analyst IV', 'grade':22, }, 
            {'position':'Supervising Administrative Officer', 'description':'Supervising Administrative Officer', 'parenthetical':'Records Offr IV', 'grade':22, }, 
            {'position':'Supervising Administrative Officer', 'description':'Supervising Administrative Officer', 'parenthetical':'Supply Offr IV', 'grade':22, }, 
            {'position':'Tailor', 'description':'Tailor', 'parenthetical':None, 'grade':3, }, 
            {'position':'Training Assistant', 'description':'Training Assistant', 'parenthetical':None, 'grade':8, }, 
            {'position':'Training Specialist I', 'description':'Training Specialist I', 'parenthetical':None, 'grade':11, }, 
            {'position':'Training Specialist II', 'description':'Training Specialist II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Training Specialist III', 'description':'Training Specialist III', 'parenthetical':None, 'grade':18, }, 
            {'position':'Training Specialist IV', 'description':'Training Specialist IV', 'parenthetical':None, 'grade':22, }, 
            {'position':'Vet Assistance Officer II', 'description':'Vet Assistance Officer II', 'parenthetical':None, 'grade':15, }, 
            {'position':'Waiter II', 'description':'Waiter II', 'parenthetical':None, 'grade':4, }, 
            {'position':'Waiter II', 'description':'Waiter II', 'parenthetical':'Waiter II', 'grade':4, }, 
            {'position':'Warehouseman II', 'description':'Warehouseman II', 'parenthetical':None, 'grade':8, },
        ]
        for row in rows:
            obj, created = Position.objects.update_or_create(
                position=row['position'], defaults=row
            )

        # SOA
        rows = [
            {'soa':'A/U (Confined)', 'description':'Attached Unassigned (Confined)', 'is_effective':True, 'with_unit':True, 'reporting':True, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'A/U (Hospitalized)', 'description':'Attached Unassigned (Hospitalized)', 'is_effective':True, 'with_unit':True, 'reporting':True, 'is_school':False, 'is_medical':True, 'is_outside':False, },
            {'soa':'TdY', 'description':'Temporary Duty', 'is_effective':True, 'with_unit':True, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'A/U (Foreign Schooling)', 'description':'Attached Unassigned (Foreign Schooling)', 'is_effective':True, 'with_unit':True, 'reporting':True, 'is_school':True, 'is_medical':False, 'is_outside':False, },
            {'soa':'Duty', 'description':None, 'is_effective':True, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'A/U (W/ Pending ESB & GCM Case)', 'description':'Attached Unassigned (W/ Pending ESB & GCM Case)', 'is_effective':False, 'with_unit':True, 'reporting':True, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'Leave', 'description':None, 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'Ordinary Leave', 'description':None, 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'SL', 'description':'Sick Leave', 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'Academic Leave', 'description':None, 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'Expanded Maternity Leave', 'description':None, 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'Paternity Leave', 'description':None, 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'Compassionate Leave', 'description':None, 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'AWOL', 'description':'Absent Without Official Leave', 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'SIQ', 'description':'Sick-in-Quarters', 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'Passes', 'description':None, 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'MWB', 'description':'Mental Wellness Break', 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'Official Mission (Foreign)', 'description':'Official Mission (Foreign)', 'is_effective':True, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'TAP', 'description':'Transition Assistance Program', 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'DS', 'description':'Detached Service', 'is_effective':False, 'with_unit':True, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'MIA', 'description':'Missing-in-Action', 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'WIA', 'description':'Wounded-in-Action', 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'KIA', 'description':'Killed-in-Action', 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'A/U (Local Schooling)', 'description':'Attached Unassigned (Local Schooling)', 'is_effective':True, 'with_unit':True, 'reporting':True, 'is_school':True, 'is_medical':False, 'is_outside':False, },
            {'soa':'Deceased', 'description':None, 'is_effective':False, 'with_unit':False, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':False, },
            {'soa':'A/U (Detailed Outside)', 'description':'Attached Unassigned (Detailed Outside)', 'is_effective':True, 'with_unit':True, 'reporting':False, 'is_school':False, 'is_medical':False, 'is_outside':True, },
        ]
        for row in rows:
            obj, created = SOA.objects.update_or_create(
                soa=row['soa'], defaults=row
            )

        # Order Types
        rows = [
            {'type':'Special Order'},
            {'type':'Reassignment Order'},
        ]
        for row in rows:
            obj, created = OrderType.objects.update_or_create(
                type=row['type'], defaults=row
            )
            
        self.stdout.write(self.style.SUCCESS('Successfully seeded the database with dummy data'))
