# Generated by Django 5.0 on 2026-03-04 05:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('unique_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('order_no', models.CharField(max_length=255, unique=True, verbose_name='Order Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date_published', models.DateField(verbose_name='Date Published')),
                ('attachment', models.FileField(upload_to='orders', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Attachment')),
                ('tags', models.TextField(blank=True, default=None, null=True, verbose_name='Tags')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedby_user_order', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Order ',
                'verbose_name_plural': 'Orders',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('office', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orderpersonnel_office', to='general.office', verbose_name='New Unit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpersonnel_order', to='orders.order', verbose_name='Order')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orderpersonnel_personnel', to='personnel.personnel', verbose_name='Personnel')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedby_user_orderpersonnel', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Order Personnel',
                'verbose_name_plural': 'Order Personnel',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.CharField(max_length=255, unique=True, verbose_name='Order Type')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatedby_user_ordertype', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Order Type',
                'verbose_name_plural': 'Order Types',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_ordertype', to='orders.ordertype', verbose_name='Order Type'),
        ),
    ]
